const STORE_INIT = { type: '@pw/STORE_INIT' };
const SYNC_INITIAL = { type: '@pw/SYNC_INITIAL' };
const SYNC_INITIAL_SUCCESS = { type: '@pw/SYNC_INITIAL_SUCCESS' };
const SYNC_INITIAL_FAIL = { type: '@pw/SYNC_INITIAL_FAIL' };

const REDUCER_SET = { type: '@pw/REDUCER_SET' };
const REDUCER_RESET = { type: '@pw/REDUCER_RESET' };
const REDUCER_REINIT = { type: '@pw/REDUCER_REINIT' };
const REDUCER_CHANGE = { type: '@pw/REDUCER_CHANGE' };

const REDUCER_READY = { type: '@pw/REDUCER_READY' };
const REDUCERS_READY = { type: '@pw/REDUCERS_READY' };

const REDUCER_REGISTER = { type: '@pw/REDUCER_REGISTER' };

export {
  STORE_INIT,
  SYNC_INITIAL,
  SYNC_INITIAL_SUCCESS,
  SYNC_INITIAL_FAIL,
  REDUCER_SET,
  REDUCER_RESET,
  REDUCER_REINIT,
  REDUCER_CHANGE,
  REDUCER_READY,
  REDUCERS_READY,
  REDUCER_REGISTER,
};
