enum POUCH_WORKER_TYPES {
  STORE_INIT = '@pw/STORE_INIT',
  REINIT_REDUCERS = '@pw/REINIT_REDUCERS',
  SYNC_INITIAL = '@pw/SYNC_INITIAL',
  SYNC_INITIAL_SUCCESS = '@pw/SYNC_INITIAL_SUCCESS',
  SYNC_INITIAL_FAIL = '@pw/SYNC_INITIAL_FAIL',
  REDUCER_SET = '@pw/REDUCER_SET',
  REDUCER_RESET = '@pw/REDUCER_RESET',
  REDUCER_REINIT = '@pw/REDUCER_REINIT',
  REDUCER_CHANGE = '@pw/REDUCER_CHANGE',
  REDUCER_READY = '@pw/REDUCER_READY',
  REDUCERS_READY = '@pw/REDUCERS_READY',
  REDUCER_REGISTER = '@pw/REDUCER_REGISTER',
}

export { POUCH_WORKER_TYPES };
